# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=b1.7.3
yarn_mappings=b1.7.3+e1fe071
loader_version=0.17.3

# Mod Properties
mod_version=1.0.1
mod_id=foodies
maven_group=io.github.sayuzaur
archives_base_name=foodies

# Dependencies
stationapi_version=2.0.0-alpha.5.4

# Extra Dependencies
gcapi_version=3.2.5
glassnetworking_version=1.0.7
alwaysmoreitems_version=1.7.1
modmenu_version=1.1.1
retrocommands_version=0.5.7
bhcreative_version=0.4.8
freecam-stapi_version=0.3.2
creativewands_version=1.4.1
